In [15]:
#working with arrays
#create a 1D array
import numpy as np
nd=np.random.randint(1,100,size=10)
print("1D data")
print("content of nd",nd)
print("type od nd",type(nd))
print("dtype of nd",nd.dtype)
print("shape of nd",nd.shape)
print("dimension of nd",nd.ndim)
print("size of nd",nd.size)

1D data
content of nd [ 9 37 50 87 53 44 60 97 23 57]
type od nd <class 'numpy.ndarray'>
dtype of nd int32
shape of nd (10,)
dimension of nd 1
size of nd 10


In [4]:
#b. create a boolean array
lst=[0,1,2,3,4,5,6,7,8]
ndo=np.array(lst,dtype=bool)
print(ndo)
ndo=ndo.reshape(3,3)
print(ndo)
print("dimension",ndo.ndim)
print("dtype",ndo.dtype)
print("shape",ndo.shape)
print("size",ndo.size)

[False  True  True  True  True  True  True  True  True]
[[False  True  True]
 [ True  True  True]
 [ True  True  True]]
dimension 2
dtype bool
shape (3, 3)
size 9


In [6]:
#c. extract items that satisfy a given condition
import numpy as np
ndo=np.random.randint(1,10,size=10)
print(ndo)
index=np.where(ndo>5)
print(index)
print(ndo[index])

[2 7 1 4 5 8 5 7 5 6]
(array([1, 5, 7, 9], dtype=int64),)
[7 8 7 6]


In [7]:
#d. replace items that satify a condition with another value in the numpy array
ts=[10,20,15,18,25,70,56]
ap=[25,19,30,45,7,89,90]
t=np.array(ts)
a=np.array(ap)
poll=np.where(t>18,t,a)
print(poll)

[25 20 30 45 25 70 56]


In [16]:
#e. replace items that satisfy a condition without affectiong the orignal array
sal=np.array([1000,2000,3000,4000,5000,6000])
comission=np.array([10,20,30,None,None,None])
newsal=np.where(comission==None,0,comission)
print(newsal)
netsal=sal+newsal
print("new salary")
print(netsal)

[10 20 30 0 0 0]
new salary
[1010 2020 3030 4000 5000 6000]


In [17]:
#f. reshape an array
ndo=np.random.randint(1,50,size=(3,3))
print(ndo)
nd1=ndo.reshape(9,)
print(nd1)

[[35 35  3]
 [24 44 48]
 [45 47 39]]
[35 35  3 24 44 48 45 47 39]


In [18]:
#g. extract all numbers between a given range from a numoy array
ndo=np.random.randint(5,10,size=8)
print(ndo)
out=np.extract(ndo>5,ndo)
print(out)

[7 7 6 6 6 8 5 7]
[7 7 6 6 6 8 7]
