In [1]:
#4.a. multidimensional array
import numpy as np
a=np.random.randint(1,100,size=(4,3))
print("Multidimensional array")
print("content of a",a)
print("Dimension of a",a.ndim)
print("dtype of a",a.dtype)
print("size of a",a.size)
print("shape of a",a.shape)
print("flat data or 1D")
print("*"*20)
b=a.reshape(12,)
print("one dimensional array")
print("content of b",b)
print("dimension of b",b.ndim)
print("dtype of b",b.dtype)
print("size of b",b.size)
print("shape of b",b.shape)
print("flat data or 1D")

Multidimensional array
content of a [[38 98 70]
 [99 93 87]
 [10 56 54]
 [10 94 95]]
Dimension of a 2
dtype of a int32
size of a 12
shape of a (4, 3)
flat data or 1D
********************
one dimensional array
content of b [38 98 70 99 93 87 10 56 54 10 94 95]
dimension of b 1
dtype of b int32
size of b 12
shape of b (12,)
flat data or 1D


In [2]:
#a. covert array into 1D
import numpy as np
a=np.random.randint(1,100,size=(4,3))
print("content of a\n",a)
b=a.reshape(12,)
print(b)

content of a
 [[72 30 21]
 [67 40 51]
 [78 53 92]
 [29 86 63]]
[72 30 21 67 40 51 78 53 92 29 86 63]


In [3]:
#4. Multidimensional arrays
#a. convert an array of arrays into flat 1d array
import numpy as np
a=np.random.randint(1,100,size=(4,3))
print("content of a",a)
for i in a:
    for j in i:
        print(j)

content of a [[10 42 93]
 [ 5  7 31]
 [91 33 92]
 [17 61 13]]
10
42
93
5
7
31
91
33
92
17
61
13


In [7]:
#4.b. swap two columns
import numpy as np
a = np.random.randint(1,300,size=(3,3))
print(a)
#fancy index
x = a[:,[2]]
y = a[:,[1]]
z = a[:,[0]]
zi = zip(x,y,z)
for i in zi:
   print(i)

[[ 56   6  67]
 [ 15  74  12]
 [ 56 204 200]]
(array([67]), array([6]), array([56]))
(array([12]), array([74]), array([15]))
(array([200]), array([204]), array([56]))


In [ ]:
#b. swap two columns
import numpy as np
a = np